#+TITLE: CIS126DL Linux Operating System
#+AUTHOR:    Dennis Kibbe
#+EMAIL:     dennis.kibbe@mesacc.edu
#+STARTUP: align
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+STYLE: <link rel="stylesheet" type="text/css" href="http://www.w3.org/StyleSheets/Core/steely.css" /> 
#+STYLE: <style type="text/css"> pre {font-size: 80%; font-weight:bold; line-height: 120%; padding-top: 0.2em; padding-bottom: 0.2em; padding-left: 1em; padding-right: 1em; border-style: solid; border-left-width: 1em; border-top-width: thin; border-right-width: thin; border-bottom-width: thin; border-color: #95ABD0; color: #00428c; background-color: #e4e5e7;} </style>
#+STYLE: <style type="text/css"> code {color: blue; font-weight:bold;} </style>
#+LINK_UP:   cis126dl.html
#+LINK_HOME: index.html
#+XSLT:

enter image description here

Did you know that you use Linux every day without knowing it? Linux powers many of the most popular sites on the web including Google, Facebook, Amazon, Twitter and many, many others.  If you own an Android phone, tablet or a Chromebook they are all based on Linux. Because of its open development model and modular construction Linux is at the forefront of innovation including the Internet of Things.

* About This Course

  In this introductory course you will learn what Linux is, how to install Linux as a virtual machine and the basics of managing a Linux operating system.  Linux skills are in high demand throughout the IT industry. Many of the topics covered in this class will help prepare you for industry certifications such as theCompTIA Linux+ and the Red Hat RHCSA.

  In this class you will be working with two popular Linux distributions Ubuntu and CentOS.  CentOS is a community supported clone of Red Hat Enterprise Linux so you will gain experience working with one of the most common Linux distributions used in business. Ubuntu is a major Linux distribution popular on the desktop.

  This is a hands-on course with approximately half the class time devoted to completing lab assignments.  The class is taught using virtual machines running in VirtualBox.  VirtualBox runs Linux as if it were another Windows or Apple application with no need to partition and format your hard drive. VirtualBox is installed on all the workstations in the classroom as well as in the Open Entry Lab. VirtualBox is Free/Open Source software which you can download and install on your own computer. Many of the assignments can also be done using live media such as a bootable DVD or USB. You will learn how to create this live media in this class.

  This course is divided into 15 modules taught over 8 weeks, each module aligning with one or more official course competencies.

* TODO Add section on class website where assignments are archived.

* About Your Instructor

Photo of the instructor

I have been teaching the Linux Operating System since 2008 at Mesa Community College and have been working with Linux for well over a decade. In 2009 I was a contributing author to The Command Line for GNU Press and have served as a subject matter expert for other publishers. Two of my courses have received Mesa Community College's Gold Star certification for instructional excellence. I hold numerous industry certifications including the CompTIA Linux+, the Linux Professional Institute LPIC-1 and the SUSE Certified Linux Administrator.  You can find a list of current and upcoming classes that I teach along with my office hours on my faculty contact page.

* Textbook

Textbook cover

The required textbook is Linux Essentials, 2nd Edition by Christine Bresnahan, Richard Blum 
September 2015 
ISBN: 978-1-119-09206-3

* Course Information

- Title :: Linux Operating System
- Section :: CIS126DL (17759)
- Credit Hours :: 3
- Prerequisites :: None
- Time :: 6:00 pm to 9:15 pm
- Days :: Tuesday and Thursday
- Dates :: May 31, 2016 to August 4, 2016
- Location :: BA 1E
- Instructor :: Dennis Kibbe
- Office :: BP 033 (Due to remodeling I will be in BA ?? this Summer)
- Phone :: 480-461-7246
- Email :: dennis.kibbe@mesacc.edu
- Class Website :: dennisk.freeshell.org

* Communication Policy

  Establishing regular and effective communications with me is the foundation of your success in this class and is a shared responsibility of instructor and student. The Canvas Inbox is the quickest way to reach me. I will respond to your inquiries within 24 hours on weekdays or by the next business day on weekends. If I do not reply in this time frame, please assume I did not receive your message and contact me again.

* Grading Standards and Practices

** Grade Weights

| Assignments   | Total Points | Final Grade         |
|---------------+--------------+---------------------|
| 6 Assignments |          150 | A 555-500 (90-100%) |
| 15 Quizzes    |          150 | B 444-500 (80-89%)  |
| Attendance    |          100 | C 388-444 (70-79%)  |
| 2 Discussions |           55 | D 233-388(60-69%)   |
| Midterm       |           50 | F 0-233 (0-59%)     |
| Final         |           50 |                     |
| Extra Credit  |           20 |                     |
|---------------+--------------+---------------------|
| Total Points  |          555 |                     |


** Quizzes

   Each week there is a quiz worth 10 points covering that week's work due before the first class session of the following week.  Quizzes not submitted by the due date will receive a grade of 0 and can not be made up. Quizzes count for 20 percent of your final grade.

** Midterm and Final Exams

   The midterm and the final exams are taken in class.  If you have a documented reason why you cannot be in class for these exams you can schedule to take a makeup exam within 48 hours of the due date otherwise you will receive a grade of 0 on the exam. I understand that to receive a final grade of C or better I must score at least 60% on the final exam. The midterm and final exams count for 40 percent of your final grade.

** Assignments and Discussions

   There is an assignment or discussion each week due the following week.  Late assignments lose 20 percent of the total point value unless you have a documented reason why the assignment could not be turned in on time.  Assignments and Discussions count for 30 percent of your final grade.

** Attendance

   See Class Participation and Drop Policy below.  Attendance counts for 10 percent of your final grade.

** Extra Credit

   Participating in the local Linux community or in a Free/Open Source project can earn you up to 10 percent of your final grade.

* Course Policies

** Community Ground Rules

   Being a member of a learning community requires one to understand, accept, and model an important set of community ground rules.  These ground rules will be in effect throughout our entire time together.  Each of us (myself included) is expected to uphold these ground rules.  Learning is a social activity and some of your best learning experiences will come from your fellow classmates. Come prepared to seek out those opportunities.  Your time in class is valuable.  Side conversations and distracting behavior can make that time less productive. Please respect your fellow classmates.  Officially food and drinks are not permitted in any of the classrooms. However, if you must eat please avoid distracting those around you.  Come prepared and be ready to participate in class. this will make class more enjoyable for all.  It's important to be available to your family even when you are in class. But please limit cellphone activity to matters that can not wait.

* Class Participation and Drop Policy

  This is a hybrid class which means that in exchange for shorter class periods you are expected to do more of the work outside of class.  You will find your time in class more enjoyable and productive if you complete the assigned reading before coming to class.  This will enable you to participate in classroom discussions and get more from classroom presentations.  I structure the class so you have time in class to complete the required lab assignments.  Many students find that they can leave class with the week's lab work already completed if they use class time wisely.  As per college policies, you are expected to attend class.  My expectation is that you come to each class, log in to Canvas no less than twice a week and complete all assignments, discussions, quizzes, and projects by the deadlines posted in Canvas.  You must have an attendance of at least 80% to pass this course with a grade of C or better.  An attendance of 75% or less will subject you to being withdrawn from class at the discretion of the instructor.  If you come to class prepared to participate and do the work you will do well in this class.

** Student Responsibilities

   As a student at MCC you are responsible for understanding and following the policies in the college catalog and student handbook.

** Services for Students that Require Special Accommodations

   Students with disabilities must have an equally effective and equivalent educational opportunity as those students without disabilities.  Students experiencing difficulty accessing course materials because of a disability are expected to contact the course instructor so that a solution can be found that provides all students equal access to course materials and technology.  If you have a documented disability, including a learning disability, and would like to discuss possible accommodations, please contact the MCC Disabilities Resources and Services (DRS) office at 480-461-7447 or drsfrontdesk@mesacc.edu.

* Changes to this Course

  Changes may be made to assignments, due dates and such during the course.  Students will be notified by the instructor of any changes in course requirements or policies.
