#+TITLE: CIS105 Survey of Computer Information Systems Syllabus
#+AUTHOR:    Dennis Kibbe
#+EMAIL:     dennis.kibbe@mesacc.edu
#+STARTUP: align
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+STYLE: <link rel="stylesheet" type="text/css" href="http://www.w3.org/StyleSheets/Core/steely.css" /> 
#+STYLE: <style type="text/css"> pre {font-size: 80%; font-weight:bold; line-height: 120%; padding-top: 0.2em; padding-bottom: 0.2em; padding-left: 1em; padding-right: 1em; border-style: solid; border-left-width: 1em; border-top-width: thin; border-right-width: thin; border-bottom-width: thin; border-color: #95ABD0; color: #00428c; background-color: #e4e5e7;} </style>
#+STYLE: <style type="text/css"> code {color: blue; font-weight:bold;} </style>
#+LINK_UP:   cis126dl.html
#+LINK_HOME: index.html
#+XSLT:

* About This Course

  This course provides an overview of computer technology, concepts, terminology, relevant emerging technologies, and the role of computers in society.  Included are discussions of social and ethical issues related to computers.  The use of word processing programs, spreadsheet, database, presentation software, and use of the Internet are included. 

* Prerequisites

  There are no official prerequisites for this class.  It is highly recommended that you are not in an English or Reading developmental education course prior to taking this class.  It is also recommended if you cannot touch-type, you may wish to learn.  Ask your instructor on how to enroll in a 1 credit touch typing class.

* Course Information

- Title :: Survey of Computer Information Systems
- Section :: 17051
- Credit Hours :: 3
- Format :: Hybrid Lecture/Lab
- Prerequisites :: None
- Course Competencies :: https://aztransmac2.asu.edu/cgi-bin/WebObjects/acres.woa/wa/freeForm2?id=49918
- Transfer :: CIS105 transfers to ASU as CIS105, NAU as CIS120, and UofA as MIS111.
- Time :: 11:20 am to 1:20 pm
- Days :: Tuesday and Thursday
- Dates :: May 31, 2016 to July 21, 2016
- Location :: BA 2E
- Instructor :: Dennis Kibbe
- Office :: BP 033 (Due to remodeling I will be in BA 025 this Summer)
- Phone :: 480-461-7246
- Email :: dennis.kibbe@mesacc.edu

* TODO About Your Instructor

Photo of the instructor

I have been teaching the Linux Operating System since 2008 at Mesa Community College and have been working with Linux for well over a decade.  In 2009 I was a contributing author to The Command Line for GNU Press and have served as a subject matter expert for other publishers.  Two of my courses have received Mesa Community College's Gold Star certification for instructional excellence.  I hold numerous industry certifications including the CompTIA Linux+, the Linux Professional Institute LPIC-1 and the SUSE Certified Linux Administrator.  You can find a list of current and upcoming classes that I teach along with my office hours on my faculty contact page.

* Textbook

This course requires an electronic (eBook) textbook.  The ebook are published by [[http://www.cengagebrain.com/shop/index.html][Cengage Publishing]] and are available at the MCC Bookstore and [[http://www.cengagebrain.com/shop/index.html][The Textbook Company]].  The book and MindTap are available as a bundle --  ISBN 9781305656512.  *You must have a MindTap subscription to complete this course!*

* About Canvas/MindTap/SAM

** Canvas

   MCC uses Canvas as its learning management system (LMS).  Canvas may be used to communicate with the instructor and classmates, submit assignments, facilitate discussions, monitor grades, and take quizzes.
   When a student enrolls at MCC, their MyMaricopa and Canvas accounts are created. Both use the the student’s MEID, which the same username and password used to log into my.maricopa.edu.

** MindTap/SAM

   MindTap an online product developed by the publisher Cengage.  SAM is an assessment manager accessed inside of MindTap.  Mindtap and SAM are used to deliver concept quizzes, graded and practice activities, online and downloaded lab assignments.  Pop-up and ad blockers must be disabled in order to use Canvas and MindTap.  If you experience any other technical problems with any part of this course, be sure to inform me right away.  I am here to help remove technical difficulties that might hinder you succeeding in this course.  *When possible keep copies of all assignments just in case electronic data is loss.*

** TODO Pop-Up Blocker

   Pop-Up blockers need to be disables to use Canvas, MindTap and SAM. This YouTube video will show you how.

*** In Windows 8

    [[https://www.youtube.com/watch?v%3DK3FB83AjRzM][How to change Pop-up Blocker Settings]] (YouTube)

    [[http://windows.microsoft.com/en-US/internet-explorer/ie-security-privacy-settings#ie%3Die-11][Change security and privacy settings for Internet Explorer]]

*** In Google Chrome

    [[https://support.google.com/chrome/answer/95472?hl%3Den][Official Chrome Support page]]

*** In Firefox

    [[https://support.mozilla.org/en-US/kb/pop-blocker-settings-exceptions-troubleshooting?redirectlocale%3Den-US&redirectslug%3DPop-up%2Bblocker][Pop-up blocker settings, exceptions and troubleshooting]]

** Cookies

** JavaScript

   

* Items you will want to have before the first day of class:

  1. Student ID Card required for lab access.  Available at the Kirk Student Center.  Students attending the Red Mountain campus need to check at the Ironwood building for Student ID cards.
  2. A set of headphones to able to hear the Mindtap tutorials in MCC's classrooms, labs, or libraries on the Southern/Dobson or Red Mountain campuses.
  3. 1GiB or larger USB flash drive or adequate cloud storage.  MCC is not responsible for any data that is lost or destroyed.

* Free Microsoft Office for Students

  Students at MCC may obtain Microsoft Office for Windows OR MAC for FREE.  [[https://www.mesacc.edu/self-help/campus-technology/free-microsoft-office-365-students-and-employees][Click here]] to get started.

* Communication Policy

  Establishing regular and effective communications with me is the foundation of your success in this class and is a shared responsibility of instructor and student. The Canvas Inbox is the quickest way to reach me.  I will respond to your inquiries within 24 hours on weekdays or by the next business day on weekends.  If I do not reply in this time frame, please assume I did not receive your message and contact me again.

* TODO Grading Standards and Practices

** Grade Weights

| Assignments   | Total Points | Final Grade         |
|---------------+--------------+---------------------|
| 6 Assignments |          150 | A 555-500 (90-100%) |
| 15 Quizzes    |          150 | B 444-500 (80-89%)  |
| Attendance    |          100 | C 388-444 (70-79%)  |
| 2 Discussions |           55 | D 233-388(60-69%)   |
| Midterm       |           50 | F 0-233 (0-59%)     |
| Final         |           50 |                     |
| Extra Credit  |           20 |                     |
|---------------+--------------+---------------------|
| Total Points  |          555 |                     |


** TODO Quizzes

   Each week there is a quiz worth 10 points covering that week's work due before the first class session of the following week.  Quizzes not submitted by the due date will receive a grade of 0 and can not be made up.  Quizzes count for 20 percent of your final grade.

** TODO Midterm and Final Exams

   The midterm and the final exams are taken in class.  If you have a documented reason why you cannot be in class for these exams you can schedule to take a makeup exam within 48 hours of the due date otherwise you will receive a grade of 0 on the exam.  I understand that to receive a final grade of C or better I must score at least 60% on the final exam. The midterm and final exams count for 40 percent of your final grade.

** TODO Assignments and Discussions

   There is an assignment or discussion each week due the following week.  Late assignments lose 20 percent of the total point value unless you have a documented reason why the assignment could not be turned in on time.  Assignments and Discussions count for 30 percent of your final grade.

** TODO Attendance

   See Class Participation and Drop Policy below.  Attendance counts for 10 percent of your final grade.

** COMMENT Extra Credit

   Participating in the local Linux community or in a Free/Open Source project can earn you up to 10 percent of your final grade.

* Course Policies

** Community Ground Rules

   Being a member of a learning community requires one to understand, accept, and model an important set of community ground rules.  These ground rules will be in effect throughout our entire time together.  Each of us (myself included) is expected to uphold these ground rules.  Learning is a social activity and some of your best learning experiences will come from your fellow classmates.  Come prepared to seek out those opportunities.  Your time in class is valuable.  Side conversations and distracting behavior can make that time less productive.  Please respect your fellow classmates.  Officially food and drinks are not permitted in any of the classrooms.  However, if you must eat please avoid distracting those around you.  Come prepared and be ready to participate in class.  this will make class more enjoyable for all.  It's important to be available to your family even when you are in class.  But please limit cellphone activity to matters that can not wait.

* Class Participation and Drop Policy

  This is a hybrid class which means that in exchange for shorter class periods you are expected to do more of the work outside of class.  You will find your time in class more enjoyable and productive if you complete the assigned reading before coming to class.  This will enable you to participate in classroom discussions and get more from classroom presentations.  I structure the class so you have time in class to complete the required lab assignments.  Many students find that they can leave class with the week's lab work already completed if they use class time wisely.  As per college policies, you are expected to attend class.  My expectation is that you come to each class, log in to the Canvas no less than twice a week and complete all assignments, discussions, quizzes, and projects by the deadlines posted in Canvas.  If you miss more than two class periods you are subject to being withdrawn from class at the discretion of the instructor.  If you come to class prepared to participate and do the work you will do well in this class.

** Student Responsibilities

   As a student at MCC you are responsible for understanding and following the policies in the college catalog and student handbook.

** Services for Students that Require Special Accommodations

   Students with disabilities must have an equally effective and equivalent educational opportunity as those students without disabilities.  Students experiencing difficulty accessing course materials because of a disability are expected to contact the course instructor so that a solution can be found that provides all students equal access to course materials and technology.  If you have a documented disability, including a learning disability, and would like to discuss possible accommodations, please contact the MCC Disabilities Resources and Services (DRS) office at 480-461-7447 or drsfrontdesk@mesacc.edu.

* Changes to this Course

  Changes may be made to assignments, due dates and such during the course.  Students will be notified by the instructor of any changes in course requirements or policies.
