#+SETUPFILE: ~/.emacs.d/org-templates/level-0.org
#+TITLE:     Managing Users and Groups
#+AUTHOR:    Dennis Kibbe
#+EMAIL:     dennis.kibbe@mesacc.edu
#+DATE:      2016-09-21 Wed
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:

* Introduction

  Managing users and groups is an important administrative skill.  In this assignment you'll add new user accounts from the command line but before doing that you need to make two changes.

** Assignment Objectives

/After successfully completing this assignment you will be able to:/

1. Create new user accounts from the command line.
2. Add a user to supplementary groups using the =usermod= command.
3. Create content in the =/etc/skel/= directory that will be copied over to the new users' home directory.
4. Modify system-wide login defaults.

** Terms and Commands You Should Know

- /etc/passwd :: A text file that describes user login accounts for the system.

- /etc/shadow :: A text file which contains the password information for the system's accounts and optional aging information.

- /etc/group :: A text file that defines the groups on the system.

- /etc/gshadow :: A text file which contains the password information for groups.

- /etc/login.defs :: A text file that defines the defaults for accounts.

- /etc/skel :: Files placed in this directory will be copied to new users home directory.

- =chage= :: Change user password expiry information.

- =groupadd= :: Create a new group.

- =groupdel= :: Remove a group from the system.

- =groupmod= :: Modify a group account.

- =passwd= :: Change a user's password.

- =useradd= :: Add a new user to the system (red Hat). The =passwd= command needs to be run to set the password for the account.

- =adduser= :: Add a new user to the system (Debian).

- =userdel= :: Remove a user.

- =usermod= :: Modify a user account.

- =vipw= :: Safely edit the =/etc/passwd=, =/etc/shadow=, and =/etc/group= files.

- =who= :: Show who is logged into the system.

- =id= :: Print real and effective user and group IDs.

- =su= :: Switch to another user (always use with the *--login* or *-l*.
	
** Preparations

   Start a Fedora virtual machine.  Commands will be different on a Debian-based machine.

** Add a File to /etc/skel

   The =/etc/skel= directory as defined in =/etc/defaults/useradd= is the place to put any files or directories you want to be copied to a user's home directory when a new user is created.  For this assignment add a /welcome.txt/ file (it can be an empty file) to the =/etc/skel= directory so it will copied to the home directories of the new accounts you create.

#+BEGIN_EXAMPLE
# touch /etc/skel/welcome.txt
#+END_EXAMPLE

** Change the Maximum Days a Password May Be Used

   The =/etc/login.defs= file sets defaults for creating user accounts such as when passwords expire.  Find the line that reads PASSMAXDAYS 99999 and change it to PASSMAXDAYS 90.  Be sure you create a backup before you edit the file.

#+BEGIN_EXAMPLE
$ su -login
# cp /etc/login.defs login.defs.bak
#+END_EXAMPLE

** Creating New Users

*** From the GUI

    Fedora has a graphical tool for creating new users.  See the Fedora System Administrative Guide under resources for how to use it to create a new user /Jay Student/.  After creating the account logout of Tux and log in as /jaystudent/.  Note that the /welcome.txt/ file you created is in the home directory.  Run =chage -l jaystudent= and note when the password will expire and that the account does not expire.

*** From the Command Line

    While still logged in as /jaystudent/ open a terminal and become root to create the second account.

    Create a second account with the login =trillian= and the passphrase =Heart of Gold=.  A passphrase can be more secure than a password since a passphrase can contain spaces and longer passphrases can be more easily remembered.

#+BEGIN_EXAMPLE
# useradd -c "Tricia McMillan, Starship Heart of Gold" trillian
# passwd trillian
#+END_EXAMPLE

**** Add a Supplemental Group

     Next add =trillian= to the =wheel= supplementary group.  Be sure to use the capital *-G* option.

#+BEGIN_EXAMPLE
# usermod -aG wheel trillian
#+END_EXAMPLE

**** Modify Account Expiration

     Next change the account expiration to 120 days from today.  First display the account entry in the =passwd= file so you can compare the entry after making the change.

#+BEGIN_EXAMPLE
$ sudo grep trillian /etc/shadow
$ sudo chage -E YYYY-MM-DD trillian
$ sudo grep trillian /etc/shadow
#+END_EXAMPLE

** What to Submit

   /Submit a screenshot of the following:/

-  The output of =id jaystudent=
-  The output of =id trillian=.
-  The output of =chage -l trillian=

** Resources

- man 5 login.defs
- man adduser
- man usermod
- man userdel
- man 5 passwd
- man passwd
- man chage
- man 5 login.defs
- [[https://docs.fedoraproject.org/en-US/Fedora/24/html/System_Administrators_Guide/index.html][Fedora 24 System Administrator's Guide]]

