#+SETUPFILE: ~/.emacs.d/org-templates/level-0.org
#+TITLE:     Managing Users and Groups
#+AUTHOR:    Dennis Kibbe
#+EMAIL:     dennis.kibbe@mesacc.edu
#+DATE:      2016-09-21 Wed
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:

* Managing Users & Groups

** Assignment Objectives

   Managing users and groups is an important administrative skill.  In this
assignment you'll add new user accounts from the command line but before
doing that you need to make two changes.

/After successfully completing this assignment you will be able to:/

1. Create new user accounts from the command line.
2. Add a user to supplementary groups with the =usermod= command.
3. Create content in the =/etc/skel/= directory that will be copied over
   to the users' home directory.
4. Describe the difference between a password and a passphrase.
5. Modify system-wide login defaults.

** Terms and Commands You Should Know

- /etc/passwd :: A text file that describes user login accounts for the
system.

- /etc/shadow :: A text file which contains the password information for
the system's accounts and optional aging information.

- /etc/group :: A text file that defines the groups on the system.

- /etc/gshadow :: A text file which contains the password information for
groups.

- /etc/login.defs :: A text file that defines the defaults for accounts.

- /etc/skel :: Files placed in this directory will be copied to new users
home directory.

- chage :: Change user password expiry information.

- groupadd :: Create a new group.

- groupdel :: Remove a group from the system.

- groupmod :: Modify a group account.

- passwd :: Change a user's password.

- useradd :: Add a new user to the system (red Hat). The =passwd= command needs to be run to set the password for the account.

- adduser :: Add a new user to the system (Debian).

- userdel :: Remove a user.

- usermod :: Modify a user account.

- vipw :: Safely edit the =/etc/passwd=, =/etc/shadow=, and =/etc/group=
files.

- who :: Show who is logged into the system.

- id :: Print real and effective user and group IDs.

- su :: Switch to another user (always use with the *--login* or *-l*.

** Preparations

   Start a CentOS 7 virtual machine.  Commands will be different on a
Debian-based machine.

** Adding a File to /etc/skel

   The =/etc/skel= directory as defined in =/etc/defaults/useradd= is the
place to put any files or directories you want to be copied to a user's
home directory when a new user is created.  For this assignment add a
welcome.txt file (it can be an empty file) to the =/etc/skel= directory
so it will copied to the home directories of the new accounts you
create.

#+BEGIN_EXAMPLE
# touch /etc/skel/welcome.txt
#+END_EXAMPLE

** Changing the Maximum Days a Password May Be Used

   The =/etc/login.defs= file sets defaults for creating user accounts such
as when passwords expire.  Find the line that reads PASSMAXDAYS 99999 and
change it to PASSMAXDAYS 90.  Be sure you create a backup before you edit
the file.

#+BEGIN_EXAMPLE
$ cd
$ cp /etc/login.defs login.defs.bak
#+END_EXAMPLE

** Creating New Users

Use the =useradd= command to create two new accounts.

*** First Account

    Create a new account with the login of =jstudent= with the password
=Pa$$w0rd=.  Use the *-c* option to add /Jill Student/ to the GECOS
field.

#+BEGIN_EXAMPLE
# useradd -c "Jill Student" jstudent
# passwd jstudent
#+END_EXAMPLE

*** Second Account

    Create a second new account with the login =trillian= and the passphrase
=Heart of Gold=.  A passphrase can be more secure than a password since a
passphrase can contain spaces and longer passphrases can be more easily
remembered.

#+BEGIN_EXAMPLE
# useradd -c "Tricia McMillan, Starship Heart of Gold" trillian
# passwd trillian
#+END_EXAMPLE

**** Add a supplemental Group

     Next add =trillian= to the =wheel= supplementary group.  /Be sure to use
the capital -G option./

#+BEGIN_EXAMPLE
# usermod -aG wheel trillian
#+END_EXAMPLE

**** Modify Account Expiration

     Next change the account expiration to 120 days from today.

#+BEGIN_EXAMPLE
$ sudo grep trillian /etc/shadow
$ sudo chage -E YYYY-MM-DD trillian
$ sudo grep trillian /etc/shadow
#+END_EXAMPLE

** What to Submit

/Submit a screenshot of the following:/

-  The output of =id jstudent=
-  The output of =id trillian=.
-  The output of =chage -l trillian=

** Resources

-  man 5 login.defs
-  man adduser
-  man usermod
-  man userdel
-  man 5 passwd
-  man passwd
-  man chage
-  man 5 login.defs

