#+TITLE: Assignment 8.1 - Archiving and Compressing Files
#+AUTHOR:    Dennis Kibbe
#+EMAIL:     dennis.kibbe@mesacc.edu
#+DESCRIPTION: Using tar to archive and compress data
#+KEYWORDS: cis238dl, tar, rhcsa
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+STYLE: <link rel="stylesheet" type="text/css" href="http://www.w3.org/StyleSheets/Core/Oldstyle" /> 
#+STYLE: <style type="text/css"> pre {font-size: 80%; font-weight:bold; line-height: 120%; padding-top: 0.2em; padding-bottom: 0.2em; padding-left: 1em; padding-right: 1em; border-style: solid; border-left-width: 1em; border-top-width: thin; border-right-width: thin; border-bottom-width: thin; border-color: #95ABD0; color: #00428c; background-color: #e4e5e7;} </style>
#+STYLE: <style type="text/css"> code {color: blue; font-weight:bold;} </style>
#+LINK_UP:   
#+LINK_HOME: index.html
#+LINK: fixme file: images/fixme.png
#+LINK: cabinet file: images/file_cabinet-40%.png
#+XSLT:

[[cabinet]]

** Introduction

The =tar= command was originally designed for backing up data to tape.  While it is still used for that purpose it is more commonly used to create a "tarball", that is an archive of files.

** Assignment Objectives

/When you have successfully completed this assignment you will be able to:/

 1. Create a tar archive with and without compression.
 2. Extract files from a tar archive.
 3. List files in a tar archive.
 4. Use =gzip= and =bzip2= to compress files.
 5. Use the =find= command to create an archive or specific files.
 6. Identify the advantages of Xz compression.

** Useful Terms

 - TAR (Tape Archive)
 - Gzip
 - Bzip2
 - Xz
 - Zip
 - Archive
 - Compression
 - Tarball
 - =find=
 - =xargs=
 - =file=

** Preparation

This assignment will work on most Linux distributions.

*** Reading

Archiving data is covered in chapter 8 of the textbook.  There is a man page for =tar= and an info page for both =tar= and =find=.

*** Create Files

Change to the =/tmp= directory and use the =dd= command to create 5 files each 1MiB in size.  This /for loop/ will create the files in one step.  After typing the first line press *Enter* bash will open a new prompt (*>*) for you to continue the command.

#+BEGIN_EXAMPLE
for i in 1 2 3 4 5
do dd if=/dev/zero of=foo$i bs=1M count=1
done
#+END_EXAMPLE

** Tape Archive (TAR)

*** Basic Syntax

The =tar= command uses the same syntax format as most commands.  Some options are required and =tar= will complain if they are not given.

: tar option(s) archive_name file_name(s)

Options can be preceded by a single dash (*-*) but it is common to omit the dash.

*** Common Options

Some of these options can not be used together. For example *c* and *x*.

| Option | Description                               |
| c      | Create archive                            |
| x      | Extract archive                           |
| t      | List files in archive                     |
| u      | Append newer files                        |
| r      | Add files to archive                      |
| d      | Compare files in archive to files on disk |

*** Create an Archive

Create a new archive including all files named *foo*.  This command will create an archive of the files you created.  By default =tar= does not compress files.

: $ tar cf foobar.tar foo*

*** List the Contents of an Archive

The *t* option will list the contents of an archive.

#+BEGIN_EXAMPLE
	$ tar tf foobar.tar
	foo1
	foo2
	foo3
	foo4
	foo5
#+END_EXAMPLE

Adding the *v* gives a more complete listing.

#+BEGIN_EXAMPLE
	$ tar tvf foobar.tar
	-rw-rw-r-- tux/tux 1048576 10:10 foo1
	-rw-rw-r-- tux/tux 1048576 10:00 foo2
	-rw-rw-r-- tux/tux 1048576 10:00 foo3
	-rw-rw-r-- tux/tux 1048576 10:00 foo4
	-rw-rw-r-- tux/tux 1048576 10:00 foo5
#+END_EXAMPLE

*** Extracting Files from an Archive

Delete all the *foo* files in the =/tmp= directory

The question mark is a wildcard character which means *foo* followed by one character.

: $ rm foo?

Then restore the files from the archive.

: $ tar xvf foobar.tar

**** Extract a Single File

Delete *foo2*.

: $ rm foo2

Now extract just *foo2* from the archive.

#+BEGIN_EXAMPLE
	$ tar xf foobar.tar foo2
	$ ls foo?
	foo1
	foo2
	foo3
	foo3
	foo4
	foo5
#+END_EXAMPLE

*** Updating Files in an Archive

You can append a newer file to the archive.  First refresh the timestamp on *foo2*.

#+BEGIN_EXAMPLE
	$ touch foo2
	ls -l foo*
#+END_EXAMPLE

/foo2/ is newer than the version in the archive.

Compare the files in the archive to those on disk.

#+BEGIN_EXAMPLE
	$ tar df foobar.tar
	foo2: Mod time differs
#+END_EXAMPLE

Add the newer /foo2/ to the archive.

: $ tar uf foobar.tar foo2

The newer file is appended to the archive.  You can update multiple files the same way.

: $ touch foo1 foo2 foo3
: $ tar uf foobar.tar foo1 foo2 foo3

The list option along with the verbose option shows the newer files.

#+BEGIN_EXAMPLE
	$ tar tvf foobar.tar
	-rw-rw-r-- tux/tux 1048576 10:18 foo1
	-rw-rw-r-- tux/tux 1048576 11:05 foo2
	-rw-rw-r-- tux/tux 1048576 10:34 foo3
	-rw-rw-r-- tux/tux 1048576 10:00 foo4
	-rw-rw-r-- tux/tux 1048576 10:00 foo5
	-rw-rw-r-- tux/tux 1048576 11:24 foo1
	-rw-rw-r-- tux/tux 1048576 11:24 foo2
	-rw-rw-r-- tux/tux 1048576 11:24 foo3
#+END_EXAMPLE

*** Using Compression

| Option | Compression |
| g      | Gzip        |
| j      | Bzip2       |
| J      | xz          |

Tar by itself does not compress the files.  Listing the files with =ls -lh foo*= shows that the archive is slightly larger that the sum of the individual files.

#+BEGIN_EXAMPLE
	$ ls -lh foo*
	-rw-rw-r-- 1 tux/tux 1.0M Nov 14 11:13 foo1
	-rw-rw-r-- 1 tux/tux 1.0M Nov 14 11:24 foo2
	-rw-rw-r-- 1 tux/tux 1.0M Nov 14 11:24 foo3
	-rw-rw-r-- 1 tux/tux 1.0M Nov 14 11:24 foo4
	-rw-rw-r-- 1 tux/tux 1.0M Nov 14 10:00 foo5
	-rw-rw-r-- 1 tux/tux 5.1M Nov 14 11:30 foobar.tar
#+END_EXAMPLE

**** Compress an Archive with Gzip

Gzip is a common compression algorithm used with =ar=.  Create a new archive with Gzip compression.

: $ tar czf foobar.tar.gz foo*

The =tar.gz= extension shows that this is a compressed archive.

#+BEGIN_EXAMPLE
	$ ls -lh foobar.tar.gz
	-rw-rw-r-- 1 tux tux 5.3K Nov 14 11:37 foobar.tar.gz
#+END_EXAMPLE

The degree of compression will depend on the type of files being compressed.  Image and sound files which are already compressed will benefit least from compression.

**** Compress an Archive with Bzip2

#+BEGIN_EXAMPLE
	$ tar cjf foobar.tar.bz2 foo*
	$ ls -lh foobar.tar.bz2
		-rw-rw-r-- 1 dennisk dennisk  715 Nov 14 11:42 foobar.tar.bz2
#+END_EXAMPLE

** Find and Tar

The =find= comamnd is useful to create an archive from a list of files.  Here =find= searchs in =/usr/share/doc/= for all text files and dumps them into a tarball.

: find /usr/share/doc/ -name *.txt | xargs tar cf archive.tar

** Extensions on the Command Line

While it is common to use extensions to make it easy to identify files types, the command line doesn't require it.  Try renaming the foo archive to something else  and then run the =file= command find its true identity.

#+BEGIN_EXAMPLE
	$ mv foobar.tar.gz foo.jpg
	$ file foo.jpg
	archive.tar.gz: gzip compressed data
#+END_EXAMPLE

Before submitting the assignment rename /foo.jpg/ back to /foobar.tar.gz/.

** What to Submit

Submit a screenshot showing the output of =tar -tvf foobar.tar.gz= showing the contents of the archive.

** Resources

 - man tar
 - info find
 - man file
 - man xargs
 - [[http://computer.howstuffworks.com/file-compression.htm][How File Compression Works]]
